default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: search_development

test:
  <<: *default
  database: search_test

production:
  <<: *default
  database: search_production
  username: search
  password: <%= ENV['SEARCH_DATABASE_PASSWORD'] %>